;  See https://tox.wiki/en/4.23.2/
[tox]
requires =
    tox>=4
    tox-uv
envlist =
    py3{12,13,14}-{latest}
skip_missing_interpreters = true

[global_var]
passenv =
    CI
    USERNAME
    # Pass user color preferences through
    PY_COLORS
    FORCE_COLOR
    NO_COLOR
    CLICOLOR
    CLICOLOR_FORCE

[testenv:latest]
description = Run tests on latest version of all dependencies (plotting not included).
passenv = {[global_var]passenv}
extras =
    test
    optional
commands =
    pytest -n auto -x

