;  See https://tox.wiki/en/4.23.2/
[tox]
requires =
    tox>=4
    tox-uv
envlist =
    py3{12,13,14}-{latest}
skip_missing_interpreters = true

[global_var]
passenv =
    CI
    USERNAME
    # Pass user color preferences through
    PY_COLORS
    FORCE_COLOR
    NO_COLOR
    CLICOLOR
    CLICOLOR_FORCE

[testenv:latest]
description = Run tests (avoid end to end tests).
passenv = {[global_var]passenv}
extras =
    test
    optional
commands =
    pytest -m 'not e2e' -n auto 

[testenv:e2e]
description = Run tests (only end to end tests).
passenv = {[global_var]passenv}
extras =
    test
    optional
    gpu
commands =
    pytest -m 'e2e' -n auto {posargs:}

[testenv:data]
description = Get data for end to end testing.
skip_install = true
passenv = {[global_var]passenv}
deps =
    datalad
allowlist_externals =
    bash
commands =
    datalad install -s https://github.com/OpenNeuroDatasets/ds001168 tests/data/ds001168
    bash -c 'datalad get -d tests/data/ds001168 tests/data/ds001168/sub-01/*/func/*rest*nii.gz -J 6'
